/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_libsdl_app_SDLActivity */

#ifndef _Included_org_libsdl_app_SDLActivity
#define _Included_org_libsdl_app_SDLActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef org_libsdl_app_SDLActivity_COMMAND_CHANGE_TITLE
#define org_libsdl_app_SDLActivity_COMMAND_CHANGE_TITLE 1L
#undef org_libsdl_app_SDLActivity_COMMAND_UNUSED
#define org_libsdl_app_SDLActivity_COMMAND_UNUSED 2L
#undef org_libsdl_app_SDLActivity_COMMAND_TEXTEDIT_HIDE
#define org_libsdl_app_SDLActivity_COMMAND_TEXTEDIT_HIDE 3L
#undef org_libsdl_app_SDLActivity_COMMAND_SET_KEEP_SCREEN_ON
#define org_libsdl_app_SDLActivity_COMMAND_SET_KEEP_SCREEN_ON 5L
#undef org_libsdl_app_SDLActivity_COMMAND_USER
#define org_libsdl_app_SDLActivity_COMMAND_USER 32768L
/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    nativeInit
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_org_libsdl_app_SDLActivity_nativeInit
        (JNIEnv *, jclass, jobject);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    nativePlay
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_libsdl_app_SDLActivity_nativePlay
        (JNIEnv *, jclass, jobject surface);

JNIEXPORT jint JNICALL
Java_org_libsdl_app_SDLActivity_nativePauseVideo(JNIEnv *, jclass);

JNIEXPORT jdouble JNICALL
Java_org_libsdl_app_SDLActivity_nativeGetPts(JNIEnv *, jclass);

JNIEXPORT jdouble JNICALL
Java_org_libsdl_app_SDLActivity_nativeGetTotalMs(JNIEnv *, jclass);

JNIEXPORT void JNICALL
Java_org_libsdl_app_SDLActivity_nativeSeekVideo(JNIEnv *, jclass,jfloat pos);
/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    nativeLowMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_nativeLowMemory
        (JNIEnv *, jclass);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    nativeQuit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_nativeQuit
        (JNIEnv *, jclass);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    nativePause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_nativePause
        (JNIEnv *, jclass);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    nativeResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_nativeResume
        (JNIEnv *, jclass);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    onNativeDropFile
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_onNativeDropFile
        (JNIEnv *, jclass, jstring);


JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_nativeSelectFile
        (JNIEnv *, jclass, jstring);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    onNativeResize
 * Signature: (IIIF)V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_onNativeResize
        (JNIEnv *, jclass, jint, jint, jint, jfloat);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    onNativePadDown
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_libsdl_app_SDLActivity_onNativePadDown
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    onNativePadUp
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_libsdl_app_SDLActivity_onNativePadUp
        (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    onNativeJoy
 * Signature: (IIF)V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_onNativeJoy
        (JNIEnv *, jclass, jint, jint, jfloat);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    onNativeHat
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_onNativeHat
        (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    onNativeKeyDown
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_onNativeKeyDown
        (JNIEnv *, jclass, jint);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    onNativeKeyUp
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_onNativeKeyUp
        (JNIEnv *, jclass, jint);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    onNativeKeyboardFocusLost
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_onNativeKeyboardFocusLost
        (JNIEnv *, jclass);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    onNativeMouse
 * Signature: (IIFF)V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_onNativeMouse
        (JNIEnv *, jclass, jint, jint, jfloat, jfloat);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    onNativeTouch
 * Signature: (IIIFFF)V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_onNativeTouch
        (JNIEnv *, jclass, jint, jint, jint, jfloat, jfloat, jfloat);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    onNativeAccel
 * Signature: (FFF)V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_onNativeAccel
        (JNIEnv *, jclass, jfloat, jfloat, jfloat);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    onNativeSurfaceChanged
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_onNativeSurfaceChanged
        (JNIEnv *, jclass);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    onNativeSurfaceDestroyed
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_libsdl_app_SDLActivity_onNativeSurfaceDestroyed
        (JNIEnv *, jclass);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    nativeAddJoystick
 * Signature: (ILjava/lang/String;IIIII)I
 */
JNIEXPORT jint JNICALL Java_org_libsdl_app_SDLActivity_nativeAddJoystick
        (JNIEnv *, jclass, jint, jstring, jint, jint, jint, jint, jint);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    nativeRemoveJoystick
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_libsdl_app_SDLActivity_nativeRemoveJoystick
        (JNIEnv *, jclass, jint);

/*
 * Class:     org_libsdl_app_SDLActivity
 * Method:    nativeGetHint
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_libsdl_app_SDLActivity_nativeGetHint
        (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
